# Generated by Django 4.1 on 2023-11-20 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона может начинаться только с 7, +7, 8 и\n                разделители только "-" или пробел.', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\n                    \\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')]),
        ),
    ]
