# Generated by Django 4.1 on 2023-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'USER'), ('Медиатор', 'MEDIATOR'), ('Администратор', 'ADMIN')], default='Пользователь', max_length=100, verbose_name='Роль'),
        ),
    ]
