# Generated by Django 4.1 on 2023-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        verbose_name='Файл',
                    ),
                ),
                ('content', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='CommentDispute',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий в споре',
                'verbose_name_plural': 'Комментарии в споре',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='',
                        verbose_name='Файл',
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'title',
                    models.CharField(max_length=50, verbose_name='Заголовок'),
                ),
                (
                    'edited_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Время изменения'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('stated', 'Решается'),
                            ('closed', 'Решено'),
                            ('not_started', 'Не рассмотрено'),
                        ],
                        max_length=20,
                        verbose_name='Статус обращения',
                    ),
                ),
                ('add_opponent', models.BooleanField(default=False)),
                (
                    'comment',
                    models.ManyToManyField(
                        through='disputes.CommentDispute',
                        to='disputes.comment',
                        verbose_name='Комментарии',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Спор',
                'verbose_name_plural': 'Споры',
            },
        ),
    ]
