# Generated by Django 4.1 on 2023-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('stated', 'Решается'), ('closed', 'Решено'), ('not_started', 'Не рассмотрено')], default='not_started', max_length=20, verbose_name='Статус обращения'),
        ),
    ]
