# Generated by Django 4.1 on 2023-10-11 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='disputes_creator',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Создатель',
            ),
        ),
        migrations.AddField(
            model_name='dispute',
            name='next_commentator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='disputes_commentator',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Следующий комментатор',
            ),
        ),
        migrations.AddField(
            model_name='dispute',
            name='opponent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='disputes_opponent',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Оппонент',
            ),
        ),
        migrations.AddField(
            model_name='commentdispute',
            name='comment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commentdisputes',
                to='disputes.comment',
                verbose_name='Комментарий',
            ),
        ),
        migrations.AddField(
            model_name='commentdispute',
            name='dispute',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commentdisputes',
                to='disputes.dispute',
                verbose_name='Спор',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to=settings.AUTH_USER_MODEL,
                verbose_name='отправитель',
            ),
        ),
    ]
