# Generated by Django 4.1 on 2023-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_alter_dispute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('Решается', 'STARTED'), ('Решено', 'CLOSED'), ('Не рассмотрено', 'NOT_STARTED')], default='Не рассмотрено', max_length=20, verbose_name='Статус обращения'),
        ),
    ]
