# Generated by Django 4.1 on 2023-10-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_alter_dispute_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='file',
        ),
        migrations.CreateModel(
            name='FileDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='disputes.dispute')),
            ],
        ),
    ]
