# Generated by Django 4.1 on 2023-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_alter_dispute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('closed', 'CLOSED'), ('not_started', 'NOT_STARTED')], default='not_started', max_length=20, verbose_name='Статус обращения'),
        ),
    ]
