# Generated by Django 4.1 on 2023-10-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_remove_comment_file_remove_dispute_file_filedispute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='disputes.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
