
version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../../.env
  backend:
    build: ../../.
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../../.env
  frontend:
    build:
      context: ../../../dispute_resolution_frontend
      dockerfile: Dockerfile
    volumes:
      - ../../../dispute_resolution_frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ../../../dispute_resolution_frontend/build:/usr/share/nginx/html/
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  static_value:
  media_value:
